[tox]
envlist = py,coverage-report,typing,lint
isolated_build = True

[testenv]
description = Run pytest against {envname}.
runner = uv-venv-lock-runner
commands =
    pytest -vvv --cov=collab_group --cov-branch --cov-report= {posargs}

[testenv:coverage-report]
description = Compile coverage from each test run.
commands = coverage report
package = skip
depends =
    py

[testenv:lint]
description = Lint codebase by running pre-commit.
commands = prek run --all-files
package = skip
uv_sync_flags = --only-group, lint

[testenv:typing]
description = Run mypy.
commands =
    mypy src/collab_group tests
package = skip
dependency_groups =
    dev
    typing
